### ISSUE TITLE
RDF Transform Export and CSRF Tokens Error 

### ISSUE THREAD

**Issue by juandql** [AtesComp/rdf-transform#21]
Hello, 

I'm currently trying to export a small table with reconciled data as an RDF turtle file. I have edited the RDF transform, to add different properties from different ontologies. Until there no problem.

When I try to export the file as turle (pretty exports) a new page with the following error message appears: 

`{"code":"error","message":"Missing or invalid csrf_token parameter"}`

I have read that starting from OpenRefine 3.3's version the command `export-rows` can still be used with POST but do not require CSRF tokens. So I don't get why I have this error message. 

I have tried to work it out, using the Postman Interceptor extension and for creating GET and POST comands and automating the generation and attribution of a csrf token, but when I run them, all I get is the following error:

```
HTTP ERROR 500 java.lang.UnsupportedOperationException

URI:  /command/core/export-rows/test_csv.ttl/csrf_token=uYzp4UhUs25Hun7ctWs4p8cjO2xH8P9j&project=2348242488516
STATUS: 500
MESSAHE: java.lang.UnsupportedOperationException
SERVLET: refine
CAUSED BY: java.lang.UnsupportedOperationException

Java.lang.UnsupportedOperationException
	at com.google.refine.commands.Command.doGet(Command.java:88)
	at com.google.refine.RefineServlet.service(RefineServlet.java:181)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
	at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1410)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:529)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:578)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1570)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:822)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1384)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1543)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1306)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at com.google.refine.ValidateHostHandler.handle(ValidateHostHandler.java:93)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.Server.handle(Server.java:563)
	at org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

Interesting enough, for all other export options from OpenRefine (e.g. CSV, HTML Table, Custom Tabular, etc) there's no error messgae and I can download the exports without problem. 

What could be happening here? I would appreciate every help :) 

FYI, I'm using:

- Windows 10 Pro 22H2 19045.5131
- OpenRefine Version 3.8.7 [TRUNK]
- Maven 3.9.9
- RDF Transform v2.2.2

And the small test project I'm trying to export is given here: 
[test.openrefine.tar.gz](https://github.com/user-attachments/files/17933955/test.openrefine.tar.gz)

Thanks!

**Comment by AtesComp** [comment]
OpenRefine was updated to add CSRF protection to commands that evaluate expressions.  All "command/core/export-rows" command now have CSRF protection.

I've added the CSRF protection to the [2.2.4 release](https://github.com/AtesComp/rdf-transform/releases/tag/v2.2.4).
